### ISSUE TITLE
parser.py uses deprecated yaml.load() call

### ISSUE THREAD

**Issue by mnijhuis-tos** [inspirehep/jsonschema2rst#13]
Using a recent pyyaml version, schema2rst from parser.py fails since it uses a [deprecated yaml.load() call](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

With a recent pyyaml version, replacing `yaml.load` by `yaml.full_load` fixes this issue. In my project I am now applying a [simple patch](https://git.astron.nl/RD/DP3/-/merge_requests/549/diffs).

Unfortunately old pyyaml versions do not have the `yaml.full_load` function and do not support the new `Loader=` argument to `yaml.load()`, so fixing this issue in parser.py may require checking the pyyaml version.

**Comment by michamos** [comment]
Fixed in https://github.com/inspirehep/jsonschema2rst/pull/15
